// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: dagger.proto

package daggerProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HgetRecord_Hget_FullMethodName = "/dagger.hgetRecord/Hget"
)

// HgetRecordClient is the client API for HgetRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HgetRecordClient interface {
	Hget(ctx context.Context, in *GetUUID, opts ...grpc.CallOption) (*UpdateObject, error)
}

type hgetRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewHgetRecordClient(cc grpc.ClientConnInterface) HgetRecordClient {
	return &hgetRecordClient{cc}
}

func (c *hgetRecordClient) Hget(ctx context.Context, in *GetUUID, opts ...grpc.CallOption) (*UpdateObject, error) {
	out := new(UpdateObject)
	err := c.cc.Invoke(ctx, HgetRecord_Hget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HgetRecordServer is the server API for HgetRecord service.
// All implementations must embed UnimplementedHgetRecordServer
// for forward compatibility
type HgetRecordServer interface {
	Hget(context.Context, *GetUUID) (*UpdateObject, error)
	mustEmbedUnimplementedHgetRecordServer()
}

// UnimplementedHgetRecordServer must be embedded to have forward compatible implementations.
type UnimplementedHgetRecordServer struct {
}

func (UnimplementedHgetRecordServer) Hget(context.Context, *GetUUID) (*UpdateObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hget not implemented")
}
func (UnimplementedHgetRecordServer) mustEmbedUnimplementedHgetRecordServer() {}

// UnsafeHgetRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HgetRecordServer will
// result in compilation errors.
type UnsafeHgetRecordServer interface {
	mustEmbedUnimplementedHgetRecordServer()
}

func RegisterHgetRecordServer(s grpc.ServiceRegistrar, srv HgetRecordServer) {
	s.RegisterService(&HgetRecord_ServiceDesc, srv)
}

func _HgetRecord_Hget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HgetRecordServer).Hget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HgetRecord_Hget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HgetRecordServer).Hget(ctx, req.(*GetUUID))
	}
	return interceptor(ctx, in, info, handler)
}

// HgetRecord_ServiceDesc is the grpc.ServiceDesc for HgetRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HgetRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dagger.hgetRecord",
	HandlerType: (*HgetRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hget",
			Handler:    _HgetRecord_Hget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dagger.proto",
}

const (
	GetRecord_Get_FullMethodName = "/dagger.getRecord/get"
)

// GetRecordClient is the client API for GetRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRecordClient interface {
	Get(ctx context.Context, in *GetUUID, opts ...grpc.CallOption) (*UpdateObject, error)
}

type getRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRecordClient(cc grpc.ClientConnInterface) GetRecordClient {
	return &getRecordClient{cc}
}

func (c *getRecordClient) Get(ctx context.Context, in *GetUUID, opts ...grpc.CallOption) (*UpdateObject, error) {
	out := new(UpdateObject)
	err := c.cc.Invoke(ctx, GetRecord_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRecordServer is the server API for GetRecord service.
// All implementations must embed UnimplementedGetRecordServer
// for forward compatibility
type GetRecordServer interface {
	Get(context.Context, *GetUUID) (*UpdateObject, error)
	mustEmbedUnimplementedGetRecordServer()
}

// UnimplementedGetRecordServer must be embedded to have forward compatible implementations.
type UnimplementedGetRecordServer struct {
}

func (UnimplementedGetRecordServer) Get(context.Context, *GetUUID) (*UpdateObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetRecordServer) mustEmbedUnimplementedGetRecordServer() {}

// UnsafeGetRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRecordServer will
// result in compilation errors.
type UnsafeGetRecordServer interface {
	mustEmbedUnimplementedGetRecordServer()
}

func RegisterGetRecordServer(s grpc.ServiceRegistrar, srv GetRecordServer) {
	s.RegisterService(&GetRecord_ServiceDesc, srv)
}

func _GetRecord_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRecordServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetRecord_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRecordServer).Get(ctx, req.(*GetUUID))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRecord_ServiceDesc is the grpc.ServiceDesc for GetRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dagger.getRecord",
	HandlerType: (*GetRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _GetRecord_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dagger.proto",
}

const (
	Builder_StartBuilding_FullMethodName = "/dagger.Builder/StartBuilding"
)

// BuilderClient is the client API for Builder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuilderClient interface {
	StartBuilding(ctx context.Context, in *BuildRoutine, opts ...grpc.CallOption) (*ReponseCode, error)
}

type builderClient struct {
	cc grpc.ClientConnInterface
}

func NewBuilderClient(cc grpc.ClientConnInterface) BuilderClient {
	return &builderClient{cc}
}

func (c *builderClient) StartBuilding(ctx context.Context, in *BuildRoutine, opts ...grpc.CallOption) (*ReponseCode, error) {
	out := new(ReponseCode)
	err := c.cc.Invoke(ctx, Builder_StartBuilding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderServer is the server API for Builder service.
// All implementations must embed UnimplementedBuilderServer
// for forward compatibility
type BuilderServer interface {
	StartBuilding(context.Context, *BuildRoutine) (*ReponseCode, error)
	mustEmbedUnimplementedBuilderServer()
}

// UnimplementedBuilderServer must be embedded to have forward compatible implementations.
type UnimplementedBuilderServer struct {
}

func (UnimplementedBuilderServer) StartBuilding(context.Context, *BuildRoutine) (*ReponseCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBuilding not implemented")
}
func (UnimplementedBuilderServer) mustEmbedUnimplementedBuilderServer() {}

// UnsafeBuilderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuilderServer will
// result in compilation errors.
type UnsafeBuilderServer interface {
	mustEmbedUnimplementedBuilderServer()
}

func RegisterBuilderServer(s grpc.ServiceRegistrar, srv BuilderServer) {
	s.RegisterService(&Builder_ServiceDesc, srv)
}

func _Builder_StartBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRoutine)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServer).StartBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Builder_StartBuilding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServer).StartBuilding(ctx, req.(*BuildRoutine))
	}
	return interceptor(ctx, in, info, handler)
}

// Builder_ServiceDesc is the grpc.ServiceDesc for Builder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Builder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dagger.Builder",
	HandlerType: (*BuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBuilding",
			Handler:    _Builder_StartBuilding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dagger.proto",
}

const (
	UpdateRecord_SendUpdate_FullMethodName = "/dagger.UpdateRecord/SendUpdate"
)

// UpdateRecordClient is the client API for UpdateRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateRecordClient interface {
	SendUpdate(ctx context.Context, in *UpdateObject, opts ...grpc.CallOption) (*ReponseCode, error)
}

type updateRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateRecordClient(cc grpc.ClientConnInterface) UpdateRecordClient {
	return &updateRecordClient{cc}
}

func (c *updateRecordClient) SendUpdate(ctx context.Context, in *UpdateObject, opts ...grpc.CallOption) (*ReponseCode, error) {
	out := new(ReponseCode)
	err := c.cc.Invoke(ctx, UpdateRecord_SendUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateRecordServer is the server API for UpdateRecord service.
// All implementations must embed UnimplementedUpdateRecordServer
// for forward compatibility
type UpdateRecordServer interface {
	SendUpdate(context.Context, *UpdateObject) (*ReponseCode, error)
	mustEmbedUnimplementedUpdateRecordServer()
}

// UnimplementedUpdateRecordServer must be embedded to have forward compatible implementations.
type UnimplementedUpdateRecordServer struct {
}

func (UnimplementedUpdateRecordServer) SendUpdate(context.Context, *UpdateObject) (*ReponseCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUpdate not implemented")
}
func (UnimplementedUpdateRecordServer) mustEmbedUnimplementedUpdateRecordServer() {}

// UnsafeUpdateRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateRecordServer will
// result in compilation errors.
type UnsafeUpdateRecordServer interface {
	mustEmbedUnimplementedUpdateRecordServer()
}

func RegisterUpdateRecordServer(s grpc.ServiceRegistrar, srv UpdateRecordServer) {
	s.RegisterService(&UpdateRecord_ServiceDesc, srv)
}

func _UpdateRecord_SendUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateRecordServer).SendUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateRecord_SendUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateRecordServer).SendUpdate(ctx, req.(*UpdateObject))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateRecord_ServiceDesc is the grpc.ServiceDesc for UpdateRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dagger.UpdateRecord",
	HandlerType: (*UpdateRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendUpdate",
			Handler:    _UpdateRecord_SendUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dagger.proto",
}
